version: '3.8'

services:
  storefront:
    image: fes0010/smart-traders-storefront:latest
    container_name: smart-traders-storefront
    restart: unless-stopped
    
    # Resource limits to prevent OOM
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # Ports
    ports:
      - "3001:3000"
    
    # Environment variables
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SUPABASE_URL=https://supabase.munene.shop
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_STORE_NAME=Smart Traders Store
      - NEXT_PUBLIC_STORE_DESCRIPTION=Quality products at great prices
      - NEXT_PUBLIC_CURRENCY=KES
      - NEXT_PUBLIC_ENABLE_REAL_TIME=true
      - NEXT_PUBLIC_SHOW_STOCK_COUNT=true
      - NEXT_PUBLIC_LOW_STOCK_THRESHOLD=10
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Networking
    networks:
      - smart-traders-network
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  smart-traders-network:
    external: true


